# Generated by Django 4.0.3 on 2022-03-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expire',
        ),
    ]
